services:
  keepass_bot:
    image: keepass-telegram-bot
    container_name: keepass-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
